import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  appShell: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  screenArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F4F8FC',
  },
  scanContainer: {
    flex: 1,
    backgroundColor: '#F4F8FC',
  },
  scanHeader: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  scanSubtitle: {
    fontSize: 15,
    color: '#667085',
    lineHeight: 21,
  },
  scrollContent: {
    paddingBottom: 24,
  },
  centerContent: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  title: {
    fontSize: 32,
    fontWeight: '700',
    color: '#1B2A41',
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 16,
    color: '#667085',
    marginBottom: 20,
    lineHeight: 22,
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: '#667085',
    textAlign: 'center',
  },
  mutedText: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  disclaimerText: {
    fontSize: 12,
    color: '#8A8A8A',
    marginTop: 15,
    marginBottom: 10,
    lineHeight: 18,
    textAlign: 'center',
  },
  dashboardCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 18,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  infoCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
  },
  cardLabel: {
    fontSize: 14,
    color: '#667085',
    marginBottom: 6,
  },
  cardNumber: {
    fontSize: 36,
    fontWeight: '700',
    color: '#1B2A41',
  },
  bpmLarge: {
    fontSize: 28,
    fontWeight: '700',
    color: '#D32F2F',
  },
  resultText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1B2A41',
    marginTop: 5,
  },
  primaryButton: {
    backgroundColor: '#1565C0',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginTop: 10,
    alignItems: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '700',
  },
  secondaryButton: {
    backgroundColor: '#FFFFFF',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginTop: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#D6DCE5',
  },
  secondaryButtonText: {
    color: '#1B2A41',
    fontSize: 16,
    fontWeight: '600',
  },
  disabledButton: {
    opacity: 0.55,
  },
  cameraPanel: {
    flex: 1,
    minHeight: 360,
    marginHorizontal: 20,
    marginBottom: 12,
    overflow: 'hidden',
    borderRadius: 18,
    backgroundColor: '#111827',
  },
  camera: {
    flex: 1,
  },
  permissionPanel: {
    flex: 1,
    justifyContent: 'center',
    padding: 24,
    backgroundColor: '#FFFFFF',
  },
  cameraControls: {
    position: 'absolute',
    bottom: 22,
    width: '100%',
    alignItems: 'center',
  },
  captureButton: {
    backgroundColor: '#1565C0',
    paddingHorizontal: 34,
    paddingVertical: 15,
    borderRadius: 30,
  },
  captureButtonText: {
    color: '#FFF',
    fontWeight: '700',
    fontSize: 17,
  },
  cameraOverlay: {
    position: 'absolute',
    top: '24%',
    left: '7%',
    width: '86%',
    height: '38%',
    borderWidth: 3,
    borderColor: '#00E676',
    borderRadius: 12,
    alignItems: 'center',
  },
  cameraOverlayText: {
    marginTop: -32,
    backgroundColor: 'rgba(0,0,0,0.65)',
    color: '#FFF',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 6,
    fontSize: 13,
  },
  importPanel: {
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  previewContainer: {
    flex: 1,
    padding: 20,
    backgroundColor: '#F4F8FC',
  },
  previewImage: {
    width: '100%',
    height: 300,
    resizeMode: 'contain',
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    marginBottom: 16,
  },
  loadingPanel: {
    alignItems: 'center',
    marginVertical: 10,
  },
  analysisHero: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderRadius: 18,
    marginBottom: 15,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  bpmHero: {
    fontSize: 44,
    fontWeight: '700',
    color: '#D32F2F',
  },
  reportCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 15,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  reportLabel: {
    fontSize: 14,
    color: '#667085',
    marginBottom: 4,
    marginTop: 8,
  },
  reportValue: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1B2A41',
  },
  reportBody: {
    fontSize: 15,
    color: '#374151',
    lineHeight: 22,
  },
  card: {
    backgroundColor: '#FFF',
    borderRadius: 15,
    padding: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  image: {
    width: '100%',
    height: 180,
    resizeMode: 'contain',
    borderRadius: 12,
    marginBottom: 12,
    backgroundColor: '#E5E7EB',
  },
  bpm: {
    fontSize: 22,
    fontWeight: '700',
    color: '#D32F2F',
    marginBottom: 6,
  },
  resultBadge: {
    alignSelf: 'flex-start',
    backgroundColor: '#E8F5E9',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    marginBottom: 6,
  },
  resultBadgeText: {
    color: '#2E7D32',
    fontWeight: '600',
  },
  modal: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.7)',
    padding: 20,
  },
  modalContent: {
    maxHeight: '88%',
    backgroundColor: '#FFF',
    borderRadius: 18,
    padding: 20,
  },
  modalImage: {
    width: '100%',
    height: 220,
    resizeMode: 'contain',
    borderRadius: 12,
    marginBottom: 15,
    backgroundColor: '#F3F4F6',
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1B2A41',
    marginBottom: 15,
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  tab: {
    flex: 1,
    alignItems: 'center',
  },
  tabText: {
    color: '#667085',
    fontWeight: '600',
    fontSize: 14,
  },
  activeTabText: {
    color: '#1565C0',
    fontWeight: '700',
  },
});
